from setuptools import setup

setup(
    name='aroon',
    version='1',
    packages=['env.Lib.site-packages.pip', 'env.Lib.site-packages.pip.req', 'env.Lib.site-packages.pip.vcs',
              'env.Lib.site-packages.pip.utils', 'env.Lib.site-packages.pip.compat', 'env.Lib.site-packages.pip.models',
              'env.Lib.site-packages.pip._vendor', 'env.Lib.site-packages.pip._vendor.idna',
              'env.Lib.site-packages.pip._vendor.certifi', 'env.Lib.site-packages.pip._vendor.chardet',
              'env.Lib.site-packages.pip._vendor.chardet.cli', 'env.Lib.site-packages.pip._vendor.distlib',
              'env.Lib.site-packages.pip._vendor.distlib._backport', 'env.Lib.site-packages.pip._vendor.urllib3',
              'env.Lib.site-packages.pip._vendor.urllib3.util', 'env.Lib.site-packages.pip._vendor.urllib3.contrib',
              'env.Lib.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'env.Lib.site-packages.pip._vendor.urllib3.packages',
              'env.Lib.site-packages.pip._vendor.urllib3.packages.backports',
              'env.Lib.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'env.Lib.site-packages.pip._vendor.colorama', 'env.Lib.site-packages.pip._vendor.html5lib',
              'env.Lib.site-packages.pip._vendor.html5lib._trie', 'env.Lib.site-packages.pip._vendor.html5lib.filters',
              'env.Lib.site-packages.pip._vendor.html5lib.treewalkers',
              'env.Lib.site-packages.pip._vendor.html5lib.treeadapters',
              'env.Lib.site-packages.pip._vendor.html5lib.treebuilders', 'env.Lib.site-packages.pip._vendor.lockfile',
              'env.Lib.site-packages.pip._vendor.progress', 'env.Lib.site-packages.pip._vendor.requests',
              'env.Lib.site-packages.pip._vendor.packaging', 'env.Lib.site-packages.pip._vendor.cachecontrol',
              'env.Lib.site-packages.pip._vendor.cachecontrol.caches', 'env.Lib.site-packages.pip._vendor.webencodings',
              'env.Lib.site-packages.pip._vendor.pkg_resources', 'env.Lib.site-packages.pip.commands',
              'env.Lib.site-packages.pip.operations', 'env.Lib.site-packages.attr', 'env.Lib.site-packages.ccxt',
              'env.Lib.site-packages.ccxt.base', 'env.Lib.site-packages.ccxt.async',
              'env.Lib.site-packages.ccxt.async.base', 'env.Lib.site-packages.idna', 'env.Lib.site-packages.pyti',
              'env.Lib.site-packages.pytz', 'env.Lib.site-packages.yarl', 'env.Lib.site-packages.numpy',
              'env.Lib.site-packages.numpy.ma', 'env.Lib.site-packages.numpy.ma.tests',
              'env.Lib.site-packages.numpy.doc', 'env.Lib.site-packages.numpy.fft',
              'env.Lib.site-packages.numpy.fft.tests', 'env.Lib.site-packages.numpy.lib',
              'env.Lib.site-packages.numpy.lib.tests', 'env.Lib.site-packages.numpy.core',
              'env.Lib.site-packages.numpy.core.tests', 'env.Lib.site-packages.numpy.f2py',
              'env.Lib.site-packages.numpy.f2py.tests', 'env.Lib.site-packages.numpy.tests',
              'env.Lib.site-packages.numpy.compat', 'env.Lib.site-packages.numpy.linalg',
              'env.Lib.site-packages.numpy.linalg.tests', 'env.Lib.site-packages.numpy.random',
              'env.Lib.site-packages.numpy.random.tests', 'env.Lib.site-packages.numpy.testing',
              'env.Lib.site-packages.numpy.testing.tests', 'env.Lib.site-packages.numpy.testing.nose_tools',
              'env.Lib.site-packages.numpy.distutils', 'env.Lib.site-packages.numpy.distutils.tests',
              'env.Lib.site-packages.numpy.distutils.command', 'env.Lib.site-packages.numpy.distutils.fcompiler',
              'env.Lib.site-packages.numpy.matrixlib', 'env.Lib.site-packages.numpy.matrixlib.tests',
              'env.Lib.site-packages.numpy.polynomial', 'env.Lib.site-packages.numpy.polynomial.tests',
              'env.Lib.site-packages.aiodns', 'env.Lib.site-packages.pandas', 'env.Lib.site-packages.pandas.io',
              'env.Lib.site-packages.pandas.io.sas', 'env.Lib.site-packages.pandas.io.json',
              'env.Lib.site-packages.pandas.io.formats', 'env.Lib.site-packages.pandas.io.msgpack',
              'env.Lib.site-packages.pandas.io.clipboard', 'env.Lib.site-packages.pandas.api',
              'env.Lib.site-packages.pandas.api.types', 'env.Lib.site-packages.pandas.core',
              'env.Lib.site-packages.pandas.core.util', 'env.Lib.site-packages.pandas.core.tools',
              'env.Lib.site-packages.pandas.core.dtypes', 'env.Lib.site-packages.pandas.core.sparse',
              'env.Lib.site-packages.pandas.core.indexes', 'env.Lib.site-packages.pandas.core.reshape',
              'env.Lib.site-packages.pandas.core.computation', 'env.Lib.site-packages.pandas.util',
              'env.Lib.site-packages.pandas._libs', 'env.Lib.site-packages.pandas._libs.tslibs',
              'env.Lib.site-packages.pandas.stats', 'env.Lib.site-packages.pandas.tests',
              'env.Lib.site-packages.pandas.tests.io', 'env.Lib.site-packages.pandas.tests.io.sas',
              'env.Lib.site-packages.pandas.tests.io.json', 'env.Lib.site-packages.pandas.tests.io.parser',
              'env.Lib.site-packages.pandas.tests.io.formats', 'env.Lib.site-packages.pandas.tests.io.msgpack',
              'env.Lib.site-packages.pandas.tests.api', 'env.Lib.site-packages.pandas.tests.util',
              'env.Lib.site-packages.pandas.tests.frame', 'env.Lib.site-packages.pandas.tests.tools',
              'env.Lib.site-packages.pandas.tests.dtypes', 'env.Lib.site-packages.pandas.tests.scalar',
              'env.Lib.site-packages.pandas.tests.series', 'env.Lib.site-packages.pandas.tests.sparse',
              'env.Lib.site-packages.pandas.tests.groupby', 'env.Lib.site-packages.pandas.tests.indexes',
              'env.Lib.site-packages.pandas.tests.indexes.period',
              'env.Lib.site-packages.pandas.tests.indexes.datetimes',
              'env.Lib.site-packages.pandas.tests.indexes.timedeltas', 'env.Lib.site-packages.pandas.tests.reshape',
              'env.Lib.site-packages.pandas.tests.tseries', 'env.Lib.site-packages.pandas.tests.indexing',
              'env.Lib.site-packages.pandas.tests.plotting', 'env.Lib.site-packages.pandas.tests.internals',
              'env.Lib.site-packages.pandas.tests.computation', 'env.Lib.site-packages.pandas.tools',
              'env.Lib.site-packages.pandas.types', 'env.Lib.site-packages.pandas.compat',
              'env.Lib.site-packages.pandas.compat.numpy', 'env.Lib.site-packages.pandas.errors',
              'env.Lib.site-packages.pandas.formats', 'env.Lib.site-packages.pandas.tseries',
              'env.Lib.site-packages.pandas.plotting', 'env.Lib.site-packages.pandas.computation',
              'env.Lib.site-packages.aiohttp', 'env.Lib.site-packages.certifi', 'env.Lib.site-packages.chardet',
              'env.Lib.site-packages.chardet.cli', 'env.Lib.site-packages.pycares', 'env.Lib.site-packages.urllib3',
              'env.Lib.site-packages.urllib3.util', 'env.Lib.site-packages.urllib3.contrib',
              'env.Lib.site-packages.urllib3.contrib._securetransport', 'env.Lib.site-packages.urllib3.packages',
              'env.Lib.site-packages.urllib3.packages.backports',
              'env.Lib.site-packages.urllib3.packages.ssl_match_hostname', 'env.Lib.site-packages.cchardet',
              'env.Lib.site-packages.dateutil', 'env.Lib.site-packages.dateutil.tz',
              'env.Lib.site-packages.dateutil.parser', 'env.Lib.site-packages.dateutil.zoneinfo',
              'env.Lib.site-packages.requests', 'env.Lib.site-packages.multidict', 'env.Lib.site-packages.setuptools',
              'env.Lib.site-packages.setuptools.extern', 'env.Lib.site-packages.setuptools._vendor',
              'env.Lib.site-packages.setuptools._vendor.packaging', 'env.Lib.site-packages.setuptools.command',
              'env.Lib.site-packages.async_timeout', 'env.Lib.site-packages.pkg_resources',
              'env.Lib.site-packages.pkg_resources.extern', 'env.Lib.site-packages.pkg_resources._vendor',
              'env.Lib.site-packages.pkg_resources._vendor.packaging'],
    url='',
    license='',
    author='ekam2',
    author_email='',
    description='aroon bot prototype'
)
